name: vgs
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - cclib
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - openpyxl
  - jupyter
