name: vgs
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.8
  - pip

  # Data science stack
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - jupyter

  # Chemistry & visualization
  - cclib
  - rdkit
  - nglview
  - openbabel  

  # Miscellaneous
  - toml

  # pip-only packages
  - pip:
      - moly==0.1.1
      - qc-iodata
      - nistchempy
